# Generated by Django 5.2.5 on 2026-01-09 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('social_media_platform', models.CharField(blank=True, max_length=100)),
                ('follower_range', models.CharField(blank=True, max_length=50)),
                ('short_pitch', models.CharField(blank=True, max_length=240)),
                ('social_media_profiles', models.JSONField(blank=True, default=list)),
                ('content_skills', models.JSONField(blank=True, default=list)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
