# Generated by Django 5.2.9 on 2026-01-06 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("paypal_email", models.EmailField(blank=True, max_length=254)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("primary_niches", models.JSONField(blank=True, default=list)),
                ("platforms", models.JSONField(blank=True, default=list)),
                ("content_style_tags", models.JSONField(blank=True, default=list)),
                ("posting_frequency", models.CharField(blank=True, max_length=80)),
                ("open_to_gifting", models.BooleanField(blank=True, null=True)),
                ("payout_method", models.CharField(blank=True, max_length=50)),
                ("tax_info", models.TextField(blank=True)),
                (
                    "onboarding_step",
                    models.CharField(
                        choices=[
                            ("identity", "Identity"),
                            ("platforms", "Platforms"),
                            ("content", "Content"),
                            ("performance", "Performance"),
                            ("payouts", "Payouts"),
                            ("complete", "Complete"),
                        ],
                        default="identity",
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("onboarding_completion_percent", models.IntegerField(default=0)),
                ("onboarding_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "onboarding_skipped_steps",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
