# Generated by Django 5.2.10 on 2026-01-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatormeta",
            name="audience_age_range",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="audience_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="average_views_per_post",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="brand_affinities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="collaboration_types",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="content_categories",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="content_formats",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="display_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="engagement_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="follower_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="posting_frequency",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="preferred_commission_range",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="primary_platform",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="social_links",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="social_platforms",
            field=models.TextField(blank=True),
        ),
    ]
