# Generated by Django 5.2.10 on 2026-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatormeta",
            name="content_languages",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="creatormeta",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
