client_id = "cc2c9329b4e81341e4b080d8950b4ed9"
name = "Badger"
application_url = "https://f501-76-169-124-226.ngrok-free.app/shopify/"
embedded = true

[auth]
redirect_urls = [
  "https://f501-76-169-124-226.ngrok-free.app/shopify/oauth/callback/"
]

[webhooks]
api_version = "2025-07"

# App lifecycle webhooks
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled/"

# Mandatory privacy compliance webhooks
[[webhooks.subscriptions]]
uri = "/webhooks/customers/data_request/"
compliance_topics = ["customers/data_request"]

[[webhooks.subscriptions]]
uri = "/webhooks/customers/redact/"
compliance_topics = ["customers/redact"]

[[webhooks.subscriptions]]
uri = "/webhooks/shop/redact/"
compliance_topics = ["shop/redact"]
