# Generated by Django 5.2.7 on 2025-11-01 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantMonthlyFee",
            fields=[],
            options={
                "verbose_name": "Merchant Monthly Fee",
                "verbose_name_plural": "Merchant Monthly Fees",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("merchants.merchantmeta",),
        ),
        migrations.CreateModel(
            name="MerchantInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paypal_invoice_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("paypal_invoice_url", models.URLField(blank=True, null=True)),
                ("status", models.CharField(default="DRAFT", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        limit_choices_to={"is_merchant": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("commission", "Commission"),
                            ("payout", "Payout"),
                            ("payment", "Payment"),
                            ("points", "Points"),
                            ("affiliate_payout", "Affiliate Payout"),
                            ("badger_payout", "Badger Payout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_creator": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries_as_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_merchant": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries_as_merchant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="ledger.merchantinvoice",
                    ),
                ),
            ],
        ),
    ]
