# Generated by Django 5.2.5 on 2026-01-09 05:15

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('shopify_product_id', models.CharField(blank=True, max_length=64, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='groups', to='merchants.merchantitem')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('shopify_access_token', models.CharField(blank=True, max_length=255)),
                ('shopify_refresh_token', models.CharField(blank=True, max_length=255)),
                ('shopify_store_domain', models.CharField(blank=True, max_length=255)),
                ('shopify_oauth_authorization_line', models.CharField(blank=True, max_length=512)),
                ('business_type', models.CharField(choices=[('independent', 'Independent'), ('shopify', 'Shopify')], default='independent', max_length=20)),
                ('billing_plan', models.CharField(choices=[('platform_only', 'Platform only ($80/mo)'), ('badger_creator', 'Badger Creator included ($30/mo)')], default='badger_creator', help_text='Choose between the platform-only plan and the plan that includes the automatic Badger creator.', max_length=32)),
                ('shopify_billing_status', models.CharField(blank=True, max_length=32)),
                ('shopify_billing_plan', models.CharField(blank=True, max_length=64)),
                ('shopify_billing_verified_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_recurring_charge_id', models.CharField(blank=True, max_length=64)),
                ('shopify_billing_confirmation_url', models.URLField(blank=True)),
                ('shopify_usage_terms', models.CharField(blank=True, max_length=255)),
                ('shopify_usage_capped_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recurring platform fee charged during each PayPal invoice cycle.', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('shopify_store_domain'), condition=models.Q(('shopify_store_domain', ''), _negated=True), name='unique_shopify_store_domain')],
            },
        ),
        migrations.CreateModel(
            name='MerchantTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'superuser')), fields=('merchant',), name='unique_superuser_per_merchant')],
            },
        ),
    ]
