# Generated by Django 5.2.4 on 2025-08-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_store_domain",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
