# Generated by Django 5.2.4 on 2025-08-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_api_password",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
