# Generated by Django 5.2.7 on 2025-10-31 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0002_merchantteammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="monthly_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Recurring platform fee charged during each PayPal invoice cycle.",
                max_digits=10,
            ),
        ),
    ]
