# Generated by Django 5.2.8 on 2025-11-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_merchantmeta_monthly_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="business_type",
            field=models.CharField(
                choices=[("independent", "Independent"), ("shopify", "Shopify")],
                default="independent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_billing_confirmation_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_billing_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_recurring_charge_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_usage_capped_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_usage_terms",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
