# Generated by Django 5.2.6 on 2025-09-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0004_itemgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantitem",
            name="shopify_product_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
