# Generated by Django 5.2.13 on 2026-04-27 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0004_merchantmeta_shopify_uninstalled_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCreatorPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("brand_awareness", "Brand awareness"),
                            ("conversions_sales", "Conversions / sales"),
                            ("website_traffic", "Website traffic"),
                            ("ugc_content_creation", "UGC content creation"),
                            ("product_launch", "Product launch"),
                            ("community_growth", "Community growth"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "campaign_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exploring", "Exploring"),
                            ("ready_to_contact", "Ready to contact"),
                            ("active_campaign", "Active campaign"),
                        ],
                        max_length=32,
                    ),
                ),
                ("preferred_creator_style", models.JSONField(blank=True, default=list)),
                (
                    "brand_tone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("casual", "Casual"),
                            ("premium", "Premium"),
                            ("playful", "Playful"),
                            ("professional", "Professional"),
                            ("science_backed", "Science-backed"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=32,
                    ),
                ),
                ("content_deliverables", models.JSONField(blank=True, default=list)),
                (
                    "performance_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reach", "Reach"),
                            ("engagement", "Engagement"),
                            ("conversions", "Conversions"),
                            ("audience_fit", "Audience fit"),
                            ("content_quality", "Content quality"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "risk_tolerance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conservative_brand_safe", "Conservative / brand-safe"),
                            ("balanced", "Balanced"),
                            (
                                "experimental_trend_driven",
                                "Experimental / trend-driven",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_500", "Under $500"),
                            ("500_1500", "$500-$1,500"),
                            ("1500_5000", "$1,500-$5,000"),
                            ("5000_plus", "$5,000+"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ideal_creator_description", models.TextField(blank=True)),
                ("brand_description", models.TextField(blank=True)),
                ("product_or_service_description", models.TextField(blank=True)),
                ("campaign_success_definition", models.TextField(blank=True)),
                ("content_to_avoid", models.TextField(blank=True)),
                ("competitor_or_conflict_notes", models.TextField(blank=True)),
                ("example_creators_or_brands", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company creator preferences",
                "verbose_name_plural": "Company creator preferences",
            },
        ),
    ]
