# Generated by Django 5.2.6 on 2025-09-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0005_merchantitem_shopify_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchantmeta",
            name="affiliate_percent",
        ),
    ]
