# Generated by Django 5.2.6 on 2025-09-07 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0005_merchantitem_shopify_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.itemgroup",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.merchantitem",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="itemgroup",
            name="items",
        ),
        migrations.AddField(
            model_name="itemgroup",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                through="merchants.ItemGroupItem",
                to="merchants.merchantitem",
            ),
        ),
    ]
