# Generated by Django 5.2.8 on 2025-11-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0005_merchantmeta_shopify_oauth_authorization_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="shopify_refresh_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
