# Generated by Django 5.2.8 on 2025-11-18 17:29

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0006_merchantmeta_shopify_refresh_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="merchantmeta",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("shopify_store_domain"),
                condition=models.Q(("shopify_store_domain", ""), _negated=True),
                name="unique_shopify_store_domain",
            ),
        ),
    ]
