# Generated by Codex on 2026-05-28

from django.db import migrations, models


def backfill_company_name(apps, schema_editor):
    MerchantMeta = apps.get_model("merchants", "MerchantMeta")
    for meta in MerchantMeta.objects.select_related("user").filter(company_name=""):
        full_name = " ".join(
            part
            for part in [
                getattr(meta.user, "first_name", ""),
                getattr(meta.user, "last_name", ""),
            ]
            if part
        )
        fallback = (
            full_name
            or meta.user.username
            or meta.user.email
            or f"Merchant {meta.user_id}"
        )
        meta.company_name = fallback[:255]
        meta.save(update_fields=["company_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0007_companycreatorpreferences_questionnaire_upgrade"),
    ]

    operations = [
        migrations.RunPython(backfill_company_name, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="merchantmeta",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
    ]
