# Generated by Django 5.2.8 on 2025-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0007_merchantmeta_unique_shopify_store_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="billing_plan",
            field=models.CharField(
                choices=[
                    ("platform_only", "Platform only ($80/mo)"),
                    ("badger_creator", "Badger Creator included ($30/mo)"),
                ],
                default="badger_creator",
                help_text="Choose between the platform-only plan and the plan that includes the automatic Badger creator.",
                max_length=32,
            ),
        ),
    ]
