# Generated by Django 6.0.6 on 2026-06-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0007_companycreatorpreferences_questionnaire_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="outreach_email",
            field=models.EmailField(
                blank=True,
                help_text="Public creator outreach contact email.",
                max_length=254,
            ),
        ),
    ]
