# Generated by Django 5.2.8 on 2025-11-19 15:52

from decimal import Decimal

from django.db import migrations, models


def set_default_plan_pricing(apps, schema_editor):
    MerchantMeta = apps.get_model("merchants", "MerchantMeta")
    for meta in MerchantMeta.objects.all():
        monthly_fee = getattr(meta, "monthly_fee", None)
        if monthly_fee is None or monthly_fee <= 0:
            meta.monthly_fee = Decimal("30.00")
            meta.save(update_fields=["monthly_fee"])


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0007_merchantmeta_unique_shopify_store_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("badger_extension", "Badger creator bundle"),
                    ("merchant_only", "Merchant only"),
                ],
                default="badger_extension",
                help_text="Choose the billing plan for this merchant. The Badger bundle includes the automatic creator and the merchant-only plan does not.",
                max_length=32,
            ),
        ),
        migrations.RunPython(set_default_plan_pricing, migrations.RunPython.noop),
    ]
