# Generated by Django 5.2.8 on 2025-11-19 01:52

import uuid
from decimal import Decimal

from django.db import migrations, models


def _resolve_link_model(apps):
    """Return a MerchantCreatorLink model that exposes the FK fields."""

    link_model = apps.get_model("links", "MerchantCreatorLink")
    field_names = {field.attname for field in link_model._meta.concrete_fields}
    if {"merchant_id", "creator_id"}.issubset(field_names):
        return link_model

    # Some environments register a historical version of the model that only
    # exposes the ``status`` field, which prevents us from filtering by the
    # foreign key identifiers. Fall back to the runtime model so we can operate
    # on the actual database schema while keeping migrations idempotent.
    from links.models import MerchantCreatorLink as RuntimeMerchantCreatorLink

    return RuntimeMerchantCreatorLink


BADGER_CREATOR_UUID = uuid.UUID("733d0d67-6a30-4c48-a92e-b8e211b490f5")


def populate_billing_plans(apps, schema_editor):
    MerchantMeta = apps.get_model("merchants", "MerchantMeta")
    CreatorMeta = apps.get_model("creators", "CreatorMeta")
    MerchantCreatorLink = _resolve_link_model(apps)
    db_alias = schema_editor.connection.alias

    try:
        badger_meta = CreatorMeta.objects.get(uuid=BADGER_CREATOR_UUID)
    except CreatorMeta.DoesNotExist:
        badger_meta = None

    for meta in MerchantMeta.objects.select_related("user"):
        if meta.monthly_fee and meta.monthly_fee >= Decimal("80.00"):
            plan = "platform_only"
            fee = Decimal("80.00")
        else:
            plan = "badger_extension"
            fee = Decimal("30.00")

        MerchantMeta.objects.filter(pk=meta.pk).update(
            billing_plan=plan,
            monthly_fee=fee,
        )

        if not badger_meta or not meta.user_id:
            continue

        if plan == "badger_extension":
            MerchantCreatorLink.objects.using(db_alias).get_or_create(
                merchant_id=meta.user_id,
                creator_id=badger_meta.user_id,
                defaults={"status": "active"},
            )
        else:
            MerchantCreatorLink.objects.using(db_alias).filter(
                merchant_id=meta.user_id,
                creator_id=badger_meta.user_id,
            ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0007_merchantmeta_unique_shopify_store_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantmeta",
            name="billing_plan",
            field=models.CharField(
                choices=[
                    ("badger_extension", "Badger Extension ($30/mo)"),
                    ("platform_only", "Platform Only ($80/mo)"),
                ],
                default="badger_extension",
                max_length=32,
            ),
        ),
        migrations.RunPython(populate_billing_plans, migrations.RunPython.noop),
    ]
