# Generated by Django 5.2.8 on 2025-11-19 18:02

from decimal import Decimal

from django.db import migrations


def align_billing_plans(apps, schema_editor):
    MerchantMeta = apps.get_model("merchants", "MerchantMeta")

    # On some installs the billing_plan column might not be available yet (for example,
    # when older databases missed migration 0008). Skip the alignment so the migration
    # can complete and the schema remains usable.
    connection = schema_editor.connection
    table_name = MerchantMeta._meta.db_table
    column_names = [
        column.name
        for column in connection.introspection.get_table_description(
            connection.cursor(), table_name
        )
    ]
    if "billing_plan" not in column_names:
        return

    for meta in MerchantMeta.objects.all():
        fee = getattr(meta, "monthly_fee", Decimal("0.00")) or Decimal("0.00")

        if fee >= Decimal("80.00"):
            meta.billing_plan = "platform_only"
            meta.monthly_fee = Decimal("80.00")
        else:
            meta.billing_plan = "badger_creator"
            if fee <= 0:
                meta.monthly_fee = Decimal("30.00")

        meta.save(update_fields=["billing_plan", "monthly_fee"])


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0008_merchantmeta_billing_plan"),
    ]

    operations = [migrations.RunPython(align_billing_plans, migrations.RunPython.noop)]
