# Generated by Django 5.2.5 on 2026-01-09 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant Configuration',
                'verbose_name_plural': 'Merchant Configuration',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('business_type', models.CharField(choices=[('independent', 'Independent'), ('shopify', 'Shopify')], default='independent', max_length=20)),
                ('auto_managed', models.BooleanField(default=False, help_text='Indicates whether this record is automatically managed based on merchant account data.')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_name', 'domain'],
            },
        ),
    ]
