# Generated by Django 5.2.8 on 2025-11-12 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchantlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchant",
            options={"ordering": ["account_name", "domain"]},
        ),
        migrations.AddField(
            model_name="merchant",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merchant_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="account_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="merchant",
            name="auto_managed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this record is automatically managed based on merchant account data.",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="business_type",
            field=models.CharField(
                choices=[("independent", "Independent"), ("shopify", "Shopify")],
                default="independent",
                max_length=20,
            ),
        ),
    ]
