# Generated by Django 5.2.8 on 2025-11-12 15:51

from __future__ import annotations

from urllib.parse import urlparse

from django.db import migrations


MERCHANT_TYPES = {"independent", "shopify"}


def _normalize(domain: str | None) -> str:
    if not domain:
        return ""

    value = domain.strip()
    if not value:
        return ""

    has_wildcard = value.startswith("*.")
    if "://" in value:
        parsed = urlparse(value)
        host = parsed.netloc or parsed.path
    else:
        host = value

    host = host.strip().lower().rstrip("/")
    if has_wildcard and not host.startswith("*."):
        host = f"*.{host.lstrip('*.')}"
    return host


def populate_managed_merchants(apps, schema_editor):
    Merchant = apps.get_model("merchantlist", "Merchant")

    # Ensure existing curated entries have a display name and type.
    for merchant in Merchant.objects.all():
        updated = False
        if not merchant.account_name:
            merchant.account_name = merchant.domain
            updated = True
        if not merchant.business_type:
            merchant.business_type = "independent"
            updated = True
        if updated:
            merchant.save(update_fields=["account_name", "business_type"])

    try:
        MerchantMeta = apps.get_model("merchants", "MerchantMeta")
    except LookupError:
        return

    for meta in MerchantMeta.objects.select_related("user"):
        domain = _normalize(getattr(meta, "shopify_store_domain", ""))
        if not domain:
            continue

        user = getattr(meta, "user", None)
        if user is not None:
            full_name_fn = getattr(user, "get_full_name", None)
            if callable(full_name_fn):
                full_name = (full_name_fn() or "").strip()
            else:
                full_name = ""

            username_fn = getattr(user, "get_username", None)
            if callable(username_fn):
                username = username_fn()
            else:
                username = getattr(user, "username", "")

            account_name = full_name or username
            account_id = user.pk
        else:
            account_name = ""
            account_id = None

        if not account_name:
            account_name = getattr(meta, "company_name", "") or domain

        business_type = getattr(meta, "business_type", "independent") or "independent"
        if business_type not in MERCHANT_TYPES:
            business_type = "independent"

        Merchant.objects.update_or_create(
            domain=domain,
            defaults={
                "account_id": account_id,
                "account_name": account_name,
                "business_type": business_type,
                "auto_managed": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("merchantlist", "0002_alter_merchant_options_merchant_account_and_more"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_managed_merchants, migrations.RunPython.noop),
    ]
