"""
Django settings for random_links project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1@#i+ivuv)%n68yqzwzg%ggqdzfqe9j$@gan+^0)!0e3%3^0x2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

MERCHANT_LIST_PATH = BASE_DIR / "merchantlist" / "static" / "merchant_list.json"
try:
    with MERCHANT_LIST_PATH.open("r", encoding="utf-8") as merchant_list_file:
        merchant_list_data = json.load(merchant_list_file)
except (OSError, ValueError, TypeError):
    merchant_domains: list[str] = []
else:
    raw_domains = merchant_list_data.get("merchants")
    merchant_domains = []
    if isinstance(raw_domains, list):
        for entry in raw_domains:
            if not isinstance(entry, str):
                continue
            domain = entry.strip().lower()
            if domain and domain not in merchant_domains:
                merchant_domains.append(domain)

for domain in merchant_domains:
    if domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(domain)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'collect',
    'accounts',
    'merchants',
    'creators',
    'customer',
    'links',
    'ledger',
    'shopify_app',
    'merchantlist',
    "verify_email.apps.VerifyEmailConfig",
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.EmailVerificationRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shopify_app.middleware.ShopifyEmbeddedAppSecurityMiddleware',
    #'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'random_links.urls'


from dotenv import load_dotenv
import os

# Load environment variables from a .env file or directory if present.
ENV_PATH = BASE_DIR / ".env"
if ENV_PATH.exists():
    if ENV_PATH.is_file():
        load_dotenv(ENV_PATH)
    else:
        def _looks_like_dotenv(path):
            filename = path.name
            return path.is_file() and (
                filename == ".env"
                or filename.endswith(".env")
                or filename.startswith(".env.")
            )

        for env_file in sorted(p for p in ENV_PATH.glob("**/*") if _looks_like_dotenv(p)):
            load_dotenv(env_file)

# Always fall back to python-dotenv's default discovery so deployments that
# rely on a standalone `.env` file continue to work without additional
# configuration.
load_dotenv()


def _normalise_origin(value: str | None) -> tuple[str | None, str | None]:
    """Return the host and origin portion of a URL or hostname."""

    if not value:
        return None, None

    candidate = value.strip()
    if not candidate:
        return None, None

    if "://" not in candidate:
        candidate = f"https://{candidate}"

    parsed = urlparse(candidate)
    if not parsed.scheme or not parsed.netloc:
        return None, None

    origin = f"{parsed.scheme}://{parsed.netloc}"
    return parsed.netloc, origin


SHOPIFY_ORIGIN_CANDIDATES = [
    os.environ.get("SHOPIFY_APP_ORIGIN"),
    os.environ.get("SHOPIFY_APP_URL"),
    os.environ.get("NGROK_URL"),
    os.environ.get("NGROK_HOST"),
    os.environ.get("SHOPIFY_APP_HOST"),
    os.environ.get("SHOPIFY_APP_DOMAIN"),
    "https://50f494970026.ngrok-free.app",
]

SHOPIFY_APP_HOST = None
SHOPIFY_APP_ORIGIN = None
for candidate in SHOPIFY_ORIGIN_CANDIDATES:
    host, origin = _normalise_origin(candidate)
    if host and origin:
        SHOPIFY_APP_HOST = host
        SHOPIFY_APP_ORIGIN = origin
        break

if SHOPIFY_APP_HOST and SHOPIFY_APP_HOST not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(SHOPIFY_APP_HOST)

_frame_ancestors = [
    "https://admin.shopify.com",
    "https://*.myshopify.com",
]
_extra_frame_ancestors = os.environ.get("SHOPIFY_FRAME_ANCESTORS")
if _extra_frame_ancestors:
    for ancestor in _extra_frame_ancestors.split(","):
        candidate = ancestor.strip()
        if candidate and candidate not in _frame_ancestors:
            _frame_ancestors.append(candidate)

SHOPIFY_EMBEDDED_APP_FRAME_ANCESTORS = tuple(_frame_ancestors)

# PayPal configuration is provided through environment variables so that
# credentials remain outside of source control.
PAYPAL_INVOICER_EMAIL = os.environ.get("PAYPAL_INVOICER_EMAIL")
PAYPAL_CLIENT_ID = os.environ.get("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.environ.get("PAYPAL_CLIENT_SECRET")
PAYPAL_OAUTH_URL = os.environ.get(
    "PAYPAL_OAUTH_URL", "https://api-m.sandbox.paypal.com/v1/oauth2/token"
)

# Shopify OAuth configuration.
SHOPIFY_API_KEY = os.environ.get("SHOPIFY_API_KEY", "")
SHOPIFY_API_SECRET = os.environ.get("SHOPIFY_API_SECRET", "")
SHOPIFY_SCOPES = os.environ.get(
    "SHOPIFY_SCOPES",
    "read_products,write_discounts",
)

_shopify_base = SHOPIFY_APP_ORIGIN.rstrip("/") if SHOPIFY_APP_ORIGIN else None
_default_shopify_app_url = (
    f"{_shopify_base}/shopify/" if _shopify_base else ""
)
_default_shopify_redirect_uri = (
    f"{_shopify_base}/shopify/oauth/callback/" if _shopify_base else ""
)

SHOPIFY_APP_URL = os.environ.get("SHOPIFY_APP_URL", _default_shopify_app_url)
SHOPIFY_REDIRECT_URI = os.environ.get(
    "SHOPIFY_REDIRECT_URI", _default_shopify_redirect_uri
)


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'random_links.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Shopify OAuth requires cross-site cookie support while the authorization
# handshake hops between Shopify and our application. Mark the session cookie as
# secure and compatible with cross-site requests so it is available during the
# callback.
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True

X_FRAME_OPTIONS = "ALLOWALL"
SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

# Email configuration is provided via environment variables (see `.env`).
# Falls back to console output during development if no settings are supplied.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 25))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "False").lower() == "true"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "webmaster@localhost"
)

CSRF_TRUSTED_ORIGINS: list[str] = []
if SHOPIFY_APP_ORIGIN:
    CSRF_TRUSTED_ORIGINS.append(SHOPIFY_APP_ORIGIN)

_extra_csrf_origins = os.environ.get("EXTRA_CSRF_TRUSTED_ORIGINS")
if _extra_csrf_origins:
    for origin in _extra_csrf_origins.split(","):
        _, normalised_origin = _normalise_origin(origin)
        if normalised_origin and normalised_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(normalised_origin)

#change url in shoplify_app/management/commands/inject_scripts_all_merchants.py if you change the ngrok URL

CORS_ALLOW_ALL_ORIGINS = True  # For development only, change for production

from corsheaders.defaults import default_headers


CORS_ALLOW_HEADERS = list(default_headers) + [
    'ngrok-skip-browser-warning',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
}

