# Generated by Django 5.2.5 on 2026-04-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_id', models.CharField(blank=True, max_length=100)),
                ('page_id', models.CharField(blank=True, max_length=100)),
                ('page_name', models.CharField(blank=True, max_length=255)),
                ('instagram_user_id', models.CharField(max_length=100, unique=True)),
                ('instagram_username', models.CharField(blank=True, max_length=255)),
                ('followers_count', models.IntegerField(default=0)),
                ('media_count', models.IntegerField(default=0)),
                ('access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
