# Generated by Django 5.2.5 on 2026-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_connect', '0003_instagram_only_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramconnection',
            name='access_token',
            field=models.TextField(blank=True),
        ),
    ]
