# Generated by Django 5.2.5 on 2026-01-09 05:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=255, unique=True)),
                ('destination_url', models.URLField()),
                ('queryParam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('storeID', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uuid', 'storeID'], name='collect_aff_uuid_08fef2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreatorMerchantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_statuses', to='creators.creatormeta')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_statuses', to='merchants.merchantmeta')),
            ],
            options={
                'verbose_name': 'Creator merchant status',
                'verbose_name_plural': 'Creator merchant statuses',
                'unique_together': {('creator', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='ReferralConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_uuid', models.UUIDField(db_index=True)),
                ('merchant_uuid', models.UUIDField(db_index=True)),
                ('order_id', models.CharField(blank=True, max_length=255)),
                ('order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_conversions', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_referral_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creator_uuid', 'merchant_uuid'], name='collect_ref_creator_ec3d03_idx'), models.Index(fields=['creator', 'merchant'], name='collect_ref_creator_12a7c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_uuid', models.UUIDField(db_index=True)),
                ('merchant_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('merchant_domain', models.CharField(blank=True, max_length=255)),
                ('landing_url', models.URLField(blank=True, max_length=1024)),
                ('landing_path', models.CharField(blank=True, max_length=512)),
                ('query_string', models.TextField(blank=True)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('referrer', models.URLField(blank=True, max_length=1024)),
                ('user_agent', models.TextField(blank=True)),
                ('visitor_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_visits', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_referral_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creator_uuid', 'merchant_uuid'], name='collect_ref_creator_9291e3_idx')],
            },
        ),
    ]
