# Generated by Django 5.2.6 on 2025-09-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0003_referralconversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True)),
                ("storeID", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["uuid", "storeID"], name="collect_aff_uuid_08fef2_idx"
                    )
                ],
            },
        ),
    ]
