# Generated by Django 5.2.6 on 2025-09-24 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect", "0004_affiliateclick"),
        ("creators", "__first__"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorMerchantStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_statuses",
                        to="creators.creatormeta",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_statuses",
                        to="merchants.merchantmeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Creator merchant status",
                "verbose_name_plural": "Creator merchant statuses",
                "unique_together": {("creator", "merchant")},
            },
        ),
    ]
