"""Database models for the Shopify app integration."""

from decimal import Decimal
from typing import Any, Dict

from django.conf import settings
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models


class Shop(models.Model):
    """Store Shopify OAuth credentials for an installed merchant."""

    shop_domain = models.CharField(max_length=255, unique=True)
    access_token = models.CharField(max_length=255)

    def __str__(self) -> str:  # pragma: no cover - helpful for admin/debugging only
        return self.shop_domain


class ShopifyChargeRecord(models.Model):
    """Audit log of Shopify billing charges generated by the platform."""

    class ChargeType(models.TextChoices):
        RECURRING = "recurring", "Recurring application charge"
        USAGE = "usage", "Usage charge"

    merchant = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="shopify_charge_records",
    )
    merchant_meta = models.ForeignKey(
        "merchants.MerchantMeta",
        on_delete=models.CASCADE,
        related_name="shopify_charge_records",
    )
    charge_type = models.CharField(max_length=20, choices=ChargeType.choices)
    shopify_charge_id = models.CharField(max_length=64, blank=True)
    name = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal("0.00"))
    currency = models.CharField(max_length=3, default="USD")
    status = models.CharField(max_length=64, blank=True)
    processed_at = models.DateTimeField(auto_now_add=True)
    raw_response = models.JSONField(blank=True, default=dict, encoder=DjangoJSONEncoder)

    class Meta:
        ordering = ("-processed_at",)

    def __str__(self) -> str:  # pragma: no cover - admin/debug helper
        label = self.get_charge_type_display() or "Charge"
        return f"{label} for {self.merchant}" if self.merchant else label

    @property
    def short_description(self) -> str:
        """Return a concise summary useful for the Django admin."""

        details = self.description or self.name
        if details:
            return details
        return f"Shopify charge {self.shopify_charge_id or 'N/A'}"

    def response_payload(self) -> Dict[str, Any]:
        """Expose the raw response data for debugging purposes."""

        return self.raw_response or {}
