# Generated by Django 6.0.6 on 2026-06-08 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(default="youtube", max_length=32)),
                ("youtube_channel_id", models.CharField(max_length=100, unique=True)),
                ("youtube_channel_title", models.CharField(blank=True, max_length=255)),
                (
                    "youtube_channel_handle",
                    models.CharField(blank=True, max_length=255),
                ),
                ("youtube_custom_url", models.CharField(blank=True, max_length=255)),
                ("subscribers_count", models.IntegerField(default=0)),
                ("video_count", models.IntegerField(default=0)),
                ("view_count", models.BigIntegerField(default=0)),
                ("youtube_access_token", models.TextField(blank=True)),
                ("youtube_refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("raw_profile_data", models.JSONField(blank=True, default=dict)),
                ("raw_channel_statistics", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
