# Generated by Django 5.2.4 on 2025-08-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key_encoded", models.CharField(blank=True, max_length=255)),
                ("api_password_encoded", models.CharField(blank=True, max_length=255)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_credential",
                        to="merchants.merchantmeta",
                    ),
                ),
            ],
        ),
    ]
