# Generated by Django 5.2.8 on 2025-11-11 06:01

import django.core.serializers.json
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0005_merchantmeta_shopify_oauth_authorization_line"),
        ("shopify_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyChargeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("recurring", "Recurring application charge"),
                            ("usage", "Usage charge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("shopify_charge_id", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("status", models.CharField(blank=True, max_length=64)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_charge_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant_meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_charge_records",
                        to="merchants.merchantmeta",
                    ),
                ),
            ],
            options={
                "ordering": ("-processed_at",),
            },
        ),
    ]
