from django.urls import path

from agent import views_outreach
from .views import (
    creator_dashboard,
    creator_agent,
    creator_agent_connectors,
    creator_earnings,
    creator_affiliate_companies,
    creator_affiliate_companies_data,
    creator_partner_messages,
    creator_my_links,
    creator_profile,
    creator_settings,
    gmail_callback,
    gmail_connect,
    gmail_disconnect,
    gmail_status,
    creator_social_media,
    creator_social_media_refresh_start,
    creator_social_media_refresh_status,
    creator_support,
    creator_marketplace,
    creator_requests,
    creator_send_request,
    delete_affiliate_merchants,
    respond_request,
)

urlpatterns = [
    path('dashboard/', creator_dashboard, name='creator_dashboard'),
    path('agent/', creator_agent, name='creator_agent'),
    path('agent/connectors/', creator_agent_connectors, name='creator_agent_connectors'),

    path('agent/outreach/businesses/search/', views_outreach.outreach_business_search, name='creator_outreach_business_search'),
    path('agent/outreach/generate/', views_outreach.outreach_generate, name='creator_outreach_generate'),
    path('agent/outreach/revise/', views_outreach.outreach_revise, name='creator_outreach_revise'),
    path('agent/outreach/search-threads/', views_outreach.outreach_search_threads, name='creator_outreach_search_threads'),
    path('agent/outreach/read-thread/', views_outreach.outreach_read_thread, name='creator_outreach_read_thread'),
    path('agent/outreach/summarize-thread/', views_outreach.outreach_summarize_thread, name='creator_outreach_summarize_thread'),
    path('agent/outreach/suggest-reply/', views_outreach.outreach_suggest_reply, name='creator_outreach_suggest_reply'),
    path('agent/outreach/next-actions/', views_outreach.outreach_next_actions, name='creator_outreach_next_actions'),
    path('agent/outreach/save-draft/', views_outreach.outreach_save_draft, name='creator_outreach_save_draft'),
    path('agent/outreach/update-draft/', views_outreach.outreach_update_draft, name='creator_outreach_update_draft'),
    path('agent/outreach/send/', views_outreach.outreach_send, name='creator_outreach_send'),
    path('agent/outreach/reply/', views_outreach.outreach_reply, name='creator_outreach_reply'),
    path('agent/outreach/drafts/', views_outreach.outreach_list_drafts, name='creator_outreach_list_drafts'),
    path('earnings/', creator_earnings, name='creator_earnings'),
    path('affiliate-companies/', creator_affiliate_companies, name='creator_affiliate_companies'),
    path('affiliate-companies/delete/', delete_affiliate_merchants, name='creator_delete_affiliations'),
    path('affiliate-companies/data/', creator_affiliate_companies_data, name='creator_affiliate_companies_data'),
    path('affiliate-companies/messages/<int:link_id>/', creator_partner_messages, name='creator_partner_messages'),
    path('my-links/', creator_my_links, name='creator_my_links'),
    path('my-links/<int:merchant_id>/', creator_my_links, name='creator_my_links_merchant'),
    path('my-links/<int:merchant_id>/<int:group_id>/', creator_my_links, name='creator_my_links_group'),
    path('profile/', creator_profile, name='creator_profile'),
    path('settings/', creator_settings, name='creator_settings'),
    path('gmail/connect/', gmail_connect, name='creator_gmail_connect'),
    path('gmail/callback/', gmail_callback, name='creator_gmail_callback'),
    path('gmail/disconnect/', gmail_disconnect, name='creator_gmail_disconnect'),
    path('gmail/status/', gmail_status, name='creator_gmail_status'),
    path('social-media/', creator_social_media, name='creator_social_media'),
    path('social-media/refresh/', creator_social_media_refresh_start, name='creator_social_media_refresh_start'),
    path('social-media/refresh/status/', creator_social_media_refresh_status, name='creator_social_media_refresh_status'),
    path('support/', creator_support, name='creator_support'),
    path('marketplace/', creator_marketplace, name='creator_marketplace'),
    path('requests/', creator_requests, name='creator_requests'),
    path('requests/send/', creator_send_request, name='creator_send_request'),
    path('respond-request/<int:link_id>/', respond_request, name='respond_request'),
]
